name: LibrarianPlus
version: '${project.version}'
main: org.milanhdev.librarianPlus.LibrarianPlus
api-version: '26.3'
commands:
  librarianmenu:
    description:
      description: Open librarian enchantment selector
      usage: /<command>